name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag your-docker-hub-username/your-docker-image-name:latest .
        working-directory: .  # Ensure the Dockerfile is present in the root directory
